### ISSUE TITLE
レベルエディタを決める

### ISSUE THREAD

**Issue by ike-jp** [punity/punity#4]
SMBライクな横スクアクションということで、レベルエディタが必要になりますが
今回のプロジェクトの大目標がPhoton+Unityを覚えることなので
レベルエディタに関しては外部ツール使いたいです。

> Tiled Map Editor
> http://www.mapeditor.org/

Phaserのとき少し触ってた感じだとすごい使いやすいです。
なんか一度変な設定触って起動しなくなったことありましたけど:joy:

この辺Unityでもローダ作ればなんとでもなるらしいので
Tiledにせよ他のにせよ、何かしら１つに絞っておきたいです。
> http://qiita.com/2dgames_jp/items/64e97d8938961dd97623

### 候補

＋Tiled Map Editor

**Comment by akai-inu** [comment]
完成度たかそう

**Comment by ike-jp** [comment]
問題なければTiledでいきたい。
Phaserで少し触ったのでたぶんロードとかおそらく実装できると思います。

実際これでいくってなったら使い方まとめます。

**Comment by ike-jp** [comment]
:pray:
