### ISSUE TITLE
ラベルを作る

### ISSUE THREAD

**Issue by ike-jp** [punity/punity#5]
issueカテゴライズしたいのでissueのラベルを設定したいです。
現状のやつは「開発準備」とかでいいと思うんですがどうでしょう？

あと英語と日本語混在してると気持ち悪いのでどちらかに統一したい。

### 候補

+ 開発準備
+ 仕様確認
+ バグ

**Comment by akai-inu** [comment]
機能ごとに `[機能]プレイヤー` とか作ると捗るよー

**Comment by ike-jp** [comment]
それだとすごい数にならないですか？そういうものなんですかね・・・？
大項目ならいいのかな～

とりあえずまだ実装段階ではないので現状は

+ 開発準備
+ 仕様
+ バグ
+ デザイン

とかで良いですかね？

**Comment by ike-jp** [comment]
done
