### ISSUE TITLE
物理エンジンを決める

### ISSUE THREAD

**Issue by ike-jp** [punity/punity#6]
物理エンジンどうしましょう？
box2dが使えるってのはチラっとみました。

SMB程度なら自前で書いてもいいのかなという気がしますが
今回の目的においてそこは重要じゃないので・・・

### 候補

+ box2d 
+ 自前でやる

**Comment by ike-jp** [comment]
デフォルトでPhysics 2D乗ってるんですね。
Physics 2Dで良い気がした。

**Comment by ike-jp** [comment]
もう少し調べます。

**Comment by akai-inu** [comment]
基本デフォルトの子で十分よねー。Rectangleの衝突判定さえ出来ればいいし。重力かけたりとか楽に出来るならなおいいし。

**Comment by ike-jp** [comment]
問題なさそうです～

クローズします
