### ISSUE TITLE
対象プラットフォームを決める

### ISSUE THREAD

**Issue by ike-jp** [punity/punity#7]
めんどうなのでWindowsのみに絞って良いのかなと思ったんですがどうでしょう？
Unityのビルド設定がよく分かってないんですが、
IOS用とかLinux用とかも依存無しにできるんですかね・・・？

個人的にはゲームパッド使いたい感
スマフォとかに対応するために入力の実装が必要になったりするのかなと思ったので
早めに決めたほうがいいのかなと思いました。

**Comment by ike-jp** [comment]
MEMO: ブラウザで良い気がした

**Comment by ike-jp** [comment]
入力インターフェイスはバーチャルパッドが簡単に実装できるらしいので
スマフォ版も案外簡単にいけそうでした

**Comment by akai-inu** [comment]
多分Input部分をいじるだけで複数プラットフォーム対応出来るけど、スマホはデプロイがめんどくさいかなーと思うからブラウザとネイティブくらいでいいんじゃないかなー。

解像度は2Dなだけあって適切な値を設定する必要がありそう。

**Comment by ike-jp** [comment]
+ Windows
+ Linux
+ ブラウザ

とりあえずこんなもんでいきますか。
Wikiに「対象プラットフォーム」記載しました。
必要が出てきたら適宜追加する形でお願いします。

クローズします～
