### ISSUE TITLE
入力インターフェイスを決める

### ISSUE THREAD

**Issue by ike-jp** [punity/punity#8]
ゲームパッドで遊びたい:pray:

#7 依存

### 候補

+ ゲームパッド

**Comment by ike-jp** [comment]
バーチャルパッドの対応がすごい簡単らしいのでスマフォ対応もすぐいけそう

> http://tsubakit1.hateblo.jp/entry/2014/10/09/035003

**Comment by akai-inu** [comment]
ゲームパッド :ok_hand:

**Comment by ike-jp** [comment]
まだ実際に触って見てないので分かりませんが
入力クラスは念のためCrossPlatformInputManagerを使う形で。

クローズします
